services:
  db:
    # image: postgres:18-bookworm
    image: postgis/postgis:18-3.6
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db-data:/var/lib/postgresql
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha-dark

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER?Variable not set}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD?Variable not set}
    volumes:
      - minio-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER?Variable not set}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD?Variable not set}
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio \"$${MINIO_ENDPOINT}\" \"$${MINIO_ROOT_USER}\" \"$${MINIO_ROOT_PASSWORD}\";
      /usr/bin/mc mb -p myminio/app-temp;
      /usr/bin/mc mb -p myminio/app-storage;
      /usr/bin/mc anonymous set public myminio/app-temp;
      /usr/bin/mc anonymous set download myminio/app-storage;
      /usr/bin/mc ilm rule add --expire-days 1 myminio/app-temp;
      /usr/bin/mc version enable myminio/app-storage;
      /usr/bin/mc ilm rule add --noncurrent-expire-days 30 --expire-delete-marker myminio/app-storage;
      exit 0;
      "

  backend:
    build:
      context: ./fastapi-backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - POSTGRES_PORT=${POSTGRES_PORT?Variable not set}
      - POSTGRES_SERVER=db
    # command: >
    #   sh -c "fastapi run main.py"

  frontend:
    build:
      context: ./next-frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    env_file:
      - .env
    # command: >
    #   sh -c "pnpm run start"

volumes:
  db-data:
    name: senior-postgis-db
  minio-data:
    name: senior-minio-data
