"""init building and building image table and relation

Revision ID: 0178a539ce68
Revises: 870ab5e2c4a7
Create Date: 2026-01-26 18:55:50.092066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0178a539ce68'
down_revision: Union[str, Sequence[str], None] = '870ab5e2c4a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('admin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_place_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_google_place_id'), 'building', ['google_place_id'], unique=True)
    op.create_index(op.f('ix_building_name'), 'building', ['name'], unique=True)
    op.create_table('building_images',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_images_building_id'), 'building_images', ['building_id'], unique=False)
    op.create_index(op.f('ix_building_images_url'), 'building_images', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_building_images_url'), table_name='building_images')
    op.drop_index(op.f('ix_building_images_building_id'), table_name='building_images')
    op.drop_table('building_images')
    op.drop_index(op.f('ix_building_name'), table_name='building')
    op.drop_index(op.f('ix_building_google_place_id'), table_name='building')
    op.drop_table('building')
    # ### end Alembic commands ###
