"""add floor field to probe

Revision ID: 06a8fc88817a
Revises: 50c1725e720c
Create Date: 2026-01-28 10:03:12.148814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '06a8fc88817a'
down_revision: Union[str, Sequence[str], None] = '50c1725e720c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('probe', sa.Column('floor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('probe', 'floor')
    # ### end Alembic commands ###
