"""init zone building relation

Revision ID: 08958e31bbc3
Revises: 0178a539ce68
Create Date: 2026-01-27 13:43:08.012720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '08958e31bbc3'
down_revision: Union[str, Sequence[str], None] = '0178a539ce68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('zone_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_building_zone_id'), 'building', ['zone_id'], unique=False)
    op.create_foreign_key(None, 'building', 'zone', ['zone_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'building', type_='foreignkey')
    op.drop_index(op.f('ix_building_zone_id'), table_name='building')
    op.drop_column('building', 'zone_id')
    # ### end Alembic commands ###
