"""init probe net field and del gl unique

Revision ID: 50c1725e720c
Revises: fff1369703ee
Create Date: 2026-01-28 01:28:34.143796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50c1725e720c'
down_revision: Union[str, Sequence[str], None] = 'fff1369703ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_building_google_place_id'), table_name='building')
    op.create_index(op.f('ix_building_google_place_id'), 'building', ['google_place_id'], unique=False)
    op.add_column('probe', sa.Column('ip_address', postgresql.INET(), nullable=True))
    op.add_column('probe', sa.Column('mac_address', postgresql.MACADDR(), nullable=True))
    op.drop_index(op.f('ix_probe_google_place_id'), table_name='probe')
    op.create_index(op.f('ix_probe_google_place_id'), 'probe', ['google_place_id'], unique=False)
    op.create_unique_constraint('uq_probe_name_building', 'probe', ['name', 'building_id'])
    op.drop_column('probe', 'ip')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('probe', sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_probe_name_building', 'probe', type_='unique')
    op.drop_index(op.f('ix_probe_google_place_id'), table_name='probe')
    op.create_index(op.f('ix_probe_google_place_id'), 'probe', ['google_place_id'], unique=True)
    op.drop_column('probe', 'mac_address')
    op.drop_column('probe', 'ip_address')
    op.drop_index(op.f('ix_building_google_place_id'), table_name='building')
    op.create_index(op.f('ix_building_google_place_id'), 'building', ['google_place_id'], unique=True)
    # ### end Alembic commands ###
