"""init zone_image and relation

Revision ID: 870ab5e2c4a7
Revises: a4025a75ef66
Create Date: 2026-01-23 23:11:32.855355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '870ab5e2c4a7'
down_revision: Union[str, Sequence[str], None] = 'a4025a75ef66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_images',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_images_url'), 'zone_images', ['url'], unique=True)
    op.create_index(op.f('ix_zone_images_zone_id'), 'zone_images', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zone_images_zone_id'), table_name='zone_images')
    op.drop_index(op.f('ix_zone_images_url'), table_name='zone_images')
    op.drop_table('zone_images')
    # ### end Alembic commands ###
