"""init probe table and relation

Revision ID: fff1369703ee
Revises: 08958e31bbc3
Create Date: 2026-01-27 22:38:00.232627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'fff1369703ee'
down_revision: Union[str, Sequence[str], None] = '08958e31bbc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probe',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_place_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_probe_building_id'), 'probe', ['building_id'], unique=False)
    op.create_index(op.f('ix_probe_google_place_id'), 'probe', ['google_place_id'], unique=True)
    op.create_index(op.f('ix_probe_name'), 'probe', ['name'], unique=False)
    op.create_index(op.f('ix_probe_serial_number'), 'probe', ['serial_number'], unique=True)
    op.create_table('probe_images',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('probe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['probe_id'], ['probe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_probe_images_probe_id'), 'probe_images', ['probe_id'], unique=False)
    op.create_index(op.f('ix_probe_images_url'), 'probe_images', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_probe_images_url'), table_name='probe_images')
    op.drop_index(op.f('ix_probe_images_probe_id'), table_name='probe_images')
    op.drop_table('probe_images')
    op.drop_index(op.f('ix_probe_serial_number'), table_name='probe')
    op.drop_index(op.f('ix_probe_name'), table_name='probe')
    op.drop_index(op.f('ix_probe_google_place_id'), table_name='probe')
    op.drop_index(op.f('ix_probe_building_id'), table_name='probe')
    op.drop_table('probe')
    # ### end Alembic commands ###
